server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist  # Use memberlist for a consistent ring

memberlist:
  join_members:
    - tempo  # Use the container name for discovery

storage:
  trace:
    backend: local
    local:
      path: /var/lib/tempo/traces

compactor:
  compaction:
    compacted_block_retention: 48h